sudo: required
services: 
    - docker

before_install:
    - docker build -t karthikkoti/react-test -f ./client/Dockerfile.dev ./client
    
script:
     - docker run -e CI=true karthikkoti/react-test npm run test -- --coverage

after_success:
    - docker build -t karthikkoti/multi-client ./client
    - docker build -t karthikkoti/multi-nginx ./nginx
    - docker build -t karthikkoti/multi-server ./server
    - docker build -t karthikkoti/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push karthikkoti/multi-client
    - docker push karthikkoti/multi-nginx
    - docker push karthikkoti/multi-server
    - docker push karthikkoti/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket: "elasticbeanstalk-us-east-2-901306329935"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"