sudo: required
services: 
    - docker

before_install:
    - docker build -t karthikkoti/react-test -f ./client/Dockerfile.dev .
    
script:
     - docker run -e CI=true karthikkoti/react-test npm run test -- --coverage

after_success:
    - docker build -t karthikkoti/multi-client ./client
    - docker build -t karthikkoti/multi-nginx ./nginx
    - docker build -t karthikkoti/multi-server ./server
    - docker build -t karthikkoti/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin